print('A soma entre int é:', 11 + 10)
print('A soma entre float é:', 11.5 + 5.5)
print('Valor booleano verdadeira:', True)
print('Valor booleano verdadeira:', False)
print('Python aqui é uma string')
